# Site settings
title: Garfield Moore
email: 
description: > # this means to ignore newlines until "baseurl:"
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://garfieldmoore.co.uk" # the base hostname & protocol for your site
twitter_username: garfieldmoore
github_username:  garfieldmoore
permalink: /:title
# Build settings
markdown: kramdown
highlighter: rouge
