# Site settings
title: Garfield Moore
email: me@garfieldmoore.co.uk
description: > # this means to ignore newlines until "baseurl:"
 I started programming back in the early 80's using Z80, &6502 assembler. I now specialise in continuous deployment, software architecture and agile development practises.
  When not programming I can be found in South East London with my partner, two lovely daughters and our assortment of cats, snakes and spiders.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://garfieldmoore.co.uk" # the base hostname & protocol for your site
twitter_username: garfieldmoore
github_username:  garfieldmoore
permalink: /:title
# Build settings
markdown: kramdown
highlighter: rouge
